version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "arbonIntensityUK/CarbonIntensityUK.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "CarbonIntensityUK/CarbonIntensityUK.csproj" }}
      - run:
          name: "Run Build step"
          command: dotnet build --configuration Release
      - run:
          name: "Test the executable"
          command: dotnet test "CarbonIntensityUK.UnitTests"
