version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    environment:
      DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "CarbonIntensityUK/CarbonIntensityUK.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "CarbonIntensityUK/CarbonIntensityUK.csproj" }}
      - run:
          name: "Run Build step"
          command: dotnet build --configuration Release
      - run:
          name: "Test the executable"
          command: dotnet test "CarbonIntensityUK.UnitTests"
